name: builds-now
on: workflow_dispatch
jobs:
  dispatch:
    strategy:
      matrix:
        type: ['lin_release', 'mac_release', 'win32_release', 'win64_release']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: ${{ matrix.type }}
